### PR TITLE
Passing integration tests for the LW Agent

### LINKED ISSUE #77: Improve error handling in LW Agent
Right now the initial version doesn't have adequate error handling.  I am worried that messages might get lost if transport fails.

We need error handling, fault injection, and  such to test and make sure that exactly once delivery happens.

### LINKED ISSUE #79: LW Agent Integration Tests
The LW Agent needs integration tests that makes sure we can read the replication stream and forward it.

### PR DESCRIPTION
**Pull request by einhverfr**
This has required a number of changes including moving the replication callback to a new thread and fully rewriting the TestDecoding parser to use RecDescent.

Fixes #79

Some error handling improvements also, fixes #77

### CODE REVIEW

**Comment by einhverfr** [comment]
One small doubt I have which I have not been able to fully test is whether the LSN stuff properly moves forward with the guard destruction moved to another thread.  For 1.0 I don't think this matters and we can find workarounds, but it would be a very good reason to come up with a fully async etcd driver.

File: lib/Bagger/Agent/LW.pm [hunk 1]
```diff
@@ -15,12 +15,17 @@ package Bagger::Agent::LW;
 
 use strict;
 use warnings;
-use Bagger::Agent::Storage::Mapper;
+use Coro;
+use Coro::AnyEvent;
```
Comment (einhverfr) [inline lib/Bagger/Agent/LW.pm:19]: Bundled with Coro inherently, so not mentioning separately in Makefile.PL

File: lib/Bagger/Agent/LW.pm [hunk 2]
```diff
@@ -15,12 +15,17 @@ package Bagger::Agent::LW;
...
+use AnyEvent;
+use AnyEvent::Loop;
```
Comment (einhverfr) [inline lib/Bagger/Agent/LW.pm:21]: Fundamentally part of AnyEvent.  Not mentioning in Makefile.PL

**Comment by einhverfr** [comment]
I have now reviewed for missing dependency additions.

File: lib/Bagger/Agent/LW.pm [hunk 3]
```diff
@@ -76,49 +81,91 @@ _recv() function.
 our %_INJECTION = ();
 
 sub _run_injection {
-    my ($injectpoint, @args) = @_;
-    return $_INJECTION{$injectpoint}(@args) if ref $_INJECTION{$injectpoint};
+    my $injectpoint = shift @_;
+    $_INJECTION{$injectpoint}(@_) if ref $_INJECTION{$injectpoint};
```
Comment (einhverfr) [inline lib/Bagger/Agent/LW.pm:85]: Re-using the argslist here is not usually considered a best practice, but here it is clear that we are just shifting one off the left side of the array and passing the rest through.  I should probably note this in the coding conventions document proposal

File: lib/Bagger/Agent/LW.pm [hunk 4]
```diff
@@ -76,49 +81,91 @@ _recv() function.
...
     my $kvstoreconfig = Bagger::Storage::Config->get('kvstore_config')->value;
    
-    my $kvstore = Bagger::Agent::KVstore->new($kvstoremod, $kvstoreconfig);
+    my $kvstore = Bagger::Agent::KVStore->new(module => $kvstoremod, config => $kvstoreconfig);
 
     # the callback is a coderef here for procesing the messages and sending them forward.
     # The bulk of the work here is in this function.
     
-    my $callback = sub {
+    my $callback = unblock_sub {
```
Comment (einhverfr) [inline lib/Bagger/Agent/LW.pm:104]: This moves the callback into a non-event-loop coroutine (and possibly different thread) and therefore makes this call asynchronous.  That prevents the etcd driver's use of blocking for events from causing the main event loop from blocking.

File: lib/Bagger/Agent/Storage/Mapper.pm [hunk 5]
```diff
@@ -78,7 +78,7 @@ my %keygen = (
 
 my %classmap = (
     'Bagger::Storage::Config'       => 'config',
-    'Bagger::Storage::Instance'     => 'postgres_instances',
+    'Bagger::Storage::Instance'     => 'postgres_instance',
```
Comment (einhverfr) [inline lib/Bagger/Agent/Storage/Mapper.pm:81]: Inconsistency in singular vs plural names is a big reason to push for the standardization on singular.

**Comment by einhverfr** [comment]
I am currently working on breaking the TestDecoding stuff off into a CPAN module.     Maybe we want to just fix the current tests and then check this ne after it that is done (hopefully in the next couple days).

**Comment by einhverfr** [comment]
This now depends on onemoredata/bagger_overpay:#4

File: Makefile.PL [hunk 6]
```diff
@@ -13,6 +13,7 @@ WriteMakefile(
                           'PGObject::Simple'                => 0,
                           'PGObject::Simple::Role'          => 0,
                           'PGObject::Util::DBMethod'        => 0,
+                          'PGObject::Util::LogRep::TestDecoding' => 0,
```
Comment (einhverfr) [inline Makefile.PL:16]: I did not re-intend the Makefile.PL here because I am concerned about repeated conflicts leading to things getting lost.   Though we have tests for this.  I think we should do another re-indent when there are fewer outstanding PRs
